import numpy as np

# 三角函数
a = np.array([0, 30, 45, 60, 90])
print('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)  # 将角度值转换为弧度后计算sin
print(sin)
print('\n')
print('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)
print(inv)
print('\n')
print('通过转化为角度制来检查结果：')
print(np.degrees(inv))
print('\n')
print('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)
print(cos)
print('\n')
print('反余弦：')
inv0 = np.arccos(cos)
print(inv0)
print('\n')
print('角度制单位：')
print(np.degrees(inv))
print('\n')
print('tan 函数：')
tan0 = np.tan(a*np.pi/180)
print(tan0)
print('\n')
print('反正切：')
inv0 = np.arctan(tan)
print(inv0)
print('\n')
print('角度制单位：')
print(np.degrees(inv))
print('\n--------------------------')

# 舍入函数
a = np.array([1.0, 5.55, 123, 0.567, 25.532])
print('原数组：')
print(a)
print('四舍五入：')
print(np.around(a))
print('向下取整：')
print(np.floor(a))
print('向上取整：')
print(np.ceil(a))